export const STRINGS = {
  en: {
    language: 'Language',
    logo: 'Online Auction',
    title: 'Log in',
    sub: 'Create auctions, track insights, and manage your inventory.',
    label: 'MSPIN',
    placeholder: 'Enter your MSPIN',
    help: "We'll text a one-time password to your registered mobile.",
    checkPre: 'I agree to the',
    terms: 'Terms and conditions',
    checkPost: '',
    cta: 'Send OTP',
    back: 'Back',
    otpTitle: 'Enter OTP',
    sentPre: 'Sent to',
    sentPost: '',
    yourMobile: 'your registered mobile',
    change: 'Change',
    otpLabel: n => `${n}-digit code`,
    digit: i => `Digit ${i}`,
    resendIn: time => `Resend code in ${time}`,
    didnt: "Didn't get it?",
    resend: 'Resend OTP',
    verify: 'Verify and log in',
    welcome: 'Welcome back',
    redirect: 'Taking you to your auction dashboard…',
    trouble: 'Trouble logging in?',
    support: 'Contact support',
    errEmpty: 'Enter your MSPIN to continue.',
    errInvalid: 'Enter a valid MSPIN.',
    errTerms: 'Accept the terms and conditions to continue.',
    errOtpLen: n => `Enter all ${n} digits of the code.`,
    errOtp: "That code didn't match. Check the SMS or resend it.",
    errGeneric: 'Something went wrong. Try again.'
  },
  hi: {
    language: 'भाषा',
    logo: 'ऑनलाइन ऑक्शन',
    title: 'लॉग इन करें',
    sub: 'नीलामी बनाएं, इनसाइट्स देखें और अपनी इन्वेंटरी मैनेज करें।',
    label: 'MSPIN',
    placeholder: 'अपना MSPIN दर्ज करें',
    help: 'हम आपके रजिस्टर्ड मोबाइल पर एक वन-टाइम पासवर्ड भेजेंगे।',
    checkPre: 'मैं',
    terms: 'नियम और शर्तों',
    checkPost: ' से सहमत हूँ',
    cta: 'OTP भेजें',
    back: 'वापस',
    otpTitle: 'OTP दर्ज करें',
    sentPre: '',
    sentPost: 'पर भेजा गया',
    yourMobile: 'आपके रजिस्टर्ड मोबाइल',
    change: 'बदलें',
    otpLabel: n => `${n} अंकों का कोड`,
    digit: i => `अंक ${i}`,
    resendIn: time => `${time} में कोड दोबारा भेजें`,
    didnt: 'कोड नहीं मिला?',
    resend: 'OTP दोबारा भेजें',
    verify: 'सत्यापित करें और लॉग इन करें',
    welcome: 'स्वागत है',
    redirect: 'आपको आपके नीलामी डैशबोर्ड पर ले जा रहे हैं…',
    trouble: 'लॉग इन में परेशानी?',
    support: 'सपोर्ट से संपर्क करें',
    errEmpty: 'आगे बढ़ने के लिए अपना MSPIN दर्ज करें।',
    errInvalid: 'मान्य MSPIN दर्ज करें।',
    errTerms: 'आगे बढ़ने के लिए नियम और शर्तें स्वीकार करें।',
    errOtpLen: n => `कोड के सभी ${n} अंक दर्ज करें।`,
    errOtp: 'कोड मेल नहीं खाया। SMS जांचें या दोबारा भेजें।',
    errGeneric: 'कुछ गलत हो गया। फिर से कोशिश करें।'
  }
};

export const LANGUAGES = [
  { code: 'en', short: 'EN', name: 'English' },
  { code: 'hi', short: 'हिं', name: 'हिन्दी' }
];
